PsicoApp/Models/ErrorViewModel.cs
namespace PsicoApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PsicoApp/Controllers/ConsultaController.cs
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PsicoApp.Data;
using System.Net.NetworkInformation;
using System.Net;

namespace PsicoApp.Controllers
{
    public class ConsultaController : Controller
    {
        private readonly IConfiguration _configuration;

        public ConsultaController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        [HttpGet]
        public IActionResult Index()
        {
            string conexion = _configuration.GetConnectionString("CadenaSQL").ToString();
            using (var con = new SqlConnection(conexion))
            {

                con.Open();
                var ListaPacientes = $"Select * from PACIENTES";
                var consulta = con.Query<Paciente>(ListaPacientes).ToList();
                return View(consulta);
            }
        }

        [HttpGet]
        public IActionResult AddConsulta()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddConsulta([FromBody] Paciente paciente)
        {
            string conexion = _configuration.GetConnectionString("CadenaSQL").ToString();
            using (var con = new SqlConnection(conexion))
            {

                con.Open();
                var queryusuario = $"Insert into PACIENTES(Nombre,Telefono,DNI,Email,Tipo,Estatus,Fecha) " +
                $"values('{paciente.Nombre}','{paciente.Telefono}','{paciente.Dni}','{paciente.Email}','{paciente.Tipo}','{paciente.Estatus}', GETDATE())";

                if (queryusuario == null)
                {
                    return View();
                }


                var ConsultaInsertada = con.Execute(queryusuario);
                return View(ConsultaInsertada);
            }

        }
        [HttpGet]
        public IActionResult EditConsultabyDNI()
        {
            return View();
        }


        [HttpPost]
        public IActionResult EditConsultabyDNI(string dni, string estatus)
        {
            string conexion = _configuration.GetConnectionString("CadenaSQL").ToString();
            using (var con = new SqlConnection(conexion))
            {

                con.Open();
                var updateQuery = $"Update PACIENTES set Estatus='{estatus}' where Dni='{dni}' ";
                var consultaPorStatus = con.Execute(updateQuery);
                return View(consultaPorStatus);
            }

        }
  
        [HttpPost]
        public IActionResult DeleteConsultabyDNI(string dni)
        {
            string conexion = _configuration.GetConnectionString("CadenaSQL").ToString();
            using (var con = new SqlConnection(conexion))
            {
                con.Open();
                var deleteQuery = $"DELETE FROM PACIENTES WHERE Dni = '{dni}'";
                var registrosEliminados = con.Execute(deleteQuery);
                return View(registrosEliminados);
            }


        }
    }
}

PsicoApp/Controllers/GaleriaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PsicoApp.Controllers
{
    public class GaleriaController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

PsicoApp/Controllers/HomeController.cs
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using PsicoApp.Data;
using PsicoApp.Models;
using System.Diagnostics;
using System.Net;
using System.Net.NetworkInformation;

namespace PsicoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly PSICOAPPContext _context;
        private readonly IConfiguration _configuration;

        public HomeController(ILogger<HomeController> logger,PSICOAPPContext context, IConfiguration configuration)
        {
            _context = context;
            _logger = logger;
            _configuration = configuration;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        
       
    }
}

PsicoApp/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System.Configuration;
using Microsoft.Extensions.Configuration;
using Microsoft.Data.SqlClient;
using Dapper;
using PsicoApp.Data;

namespace PsicoApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly IConfiguration _configuration;

        public LoginController(IConfiguration configuration) {

            _configuration = configuration;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost] 
        public IActionResult Index(string dni,string password)
        {
            if (string.IsNullOrEmpty(dni) && string.IsNullOrEmpty(password))
            {
                return View();
            }
            string conexion = _configuration.GetConnectionString("CadenaSQL").ToString();
           
            using (var con = new SqlConnection(conexion))
            {
               
                con.Open();
                var queryusuario = $"Select * from USUARIOS where DNI='{dni}'";
                var usuarioEncontrado = con.QueryFirstOrDefault<Usuario>(queryusuario);

                if (dni==usuarioEncontrado.Dni && password==usuarioEncontrado.Password)
                {
                    return RedirectToAction("Index", "Galeria");
                }
                con.Close();
            }
            return View();
                
            
            
        }
        [HttpGet]
        public IActionResult Registro()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Registro(string DNI, string password, string nombre)
        {
            string conexion = _configuration.GetConnectionString("CadenaSQL").ToString();

            using (var con = new SqlConnection(conexion))
            {

                con.Open();
                var queryusuario = $"Insert into USUARIOS(Nombre,Password,DNI) values('{nombre}','{password}','{DNI}')";
                var usuarioEncontrado = con.Execute(queryusuario);
            }

            return RedirectToAction("Index", "Login");
        }
    }
}

PsicoApp/Controllers/PreciosController.cs
using Microsoft.AspNetCore.Mvc;

namespace PsicoApp.Controllers
{
    public class PreciosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PsicoApp/Views/Consulta/Index.cshtml
@model List<PsicoApp.Data.Paciente>


<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">DNI</th>
            <th scope="col">Nombre</th>
            <th scope="col">Telefono</th>
            <th scope="col">Email</th>
            <th scope="col">Estatus</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Dni</td>
                <td>@item.Nombre</td>
                <td>@item.Telefono</td>
                <td>@item.Email</td>
                @if (item.Estatus == "pendiente")
                {
                    <td><span class="badge text-bg-warning text-black">@item.Estatus</span></td>

                }

                <td><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Agregar</button></td>
                <td><button class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#EditModal">Editar</button></td>
                <td>
                    <form asp-controller="Consultas" asp-action="DeleteConsultabyDNI" method="post">
                        <button class="btn btn-danger" type="submit">Eliminar</button>

                    </form>
                </td>
            </tr>
        }



    </tbody>
</table>


<!-- Modal -->
<div class="modal fade" id="EditModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Editar Cita</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Ingrese su DNI</label>
                    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="987654321">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Ingrese su Nombre</label>
                    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Ingrese su Telefono sin guiones</label>
                    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="1234356789">
                </div>
                
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Direccion</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="1"></textarea>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Ingrese su Email</label>
                    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                </div>





            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Agregar Cita</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="exampleFormControlInput1DNI" class="form-label">Ingrese su DNI</label>
                    <input type="email" class="form-control" name="dni" id="exampleFormControlInput1DNI" placeholder="987654321">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1Nombre" class="form-label">Ingrese su Nombre</label>
                    <input type="email" class="form-control" name="nombre" id="exampleFormControlInput1Nombre" placeholder="name@example.com">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1Telefono" class="form-label">Ingrese su Telefono sin guiones</label>
                    <input type="email" class="form-control" name="telefono" id="exampleFormControlInput1Telefono" placeholder="1234356789">
                </div>

                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Direccion</label>
                    <textarea class="form-control" name="direccion" id="exampleFormControlTextarea1" rows="1"></textarea>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1Email" class="form-label">Ingrese su Email</label>
                    <input type="email" class="form-control"name="email" id="exampleFormControlInput1Email" placeholder="name@example.com">
                </div>





            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" id="btnSaveChanges" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('btnSaveChanges').addEventListener('click', function () {
        // Obtén los valores de los campos del modal
        var dni = document.getElementById('exampleFormControlInput1DNI').value;
        var nombre = document.getElementById('exampleFormControlInput1Nombre').value;
        var telefono = document.getElementById('exampleFormControlInput1Telefono').value;
        var direccion = document.getElementById('exampleFormControlTextarea1').value;
        var email = document.getElementById('exampleFormControlInput1Email').value;
        var estatus="pendiente"
        // Crea un objeto que contenga los datos
        var data = {
            nombre: nombre,
            telefono: telefono,
            dni: dni,
            departamento: '', // No se está utilizando en la acción del controlador
            email: email,
            tipo: '', // No se está utilizando en la acción del controlador
            estatus: estatus
        };


        // Realiza la solicitud Fetch al controlador en C# para guardar los datos
        fetch('/Consulta/AddConsulta', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        })
            .then(response => response.json())
            .then(data => {
                Swall.fire(
                    'Se ha ingresado la cita correctamente',
                    'Success'
                )
            })
            .catch(error => {
                // Manejar errores si la solicitud falla
                console.error('Error:', error);
            });
    });
</script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

PsicoApp/Views/Galeria/Index.cshtml
    <main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Album del Podcast</h1>
                <p class="lead text-body-secondary">Aqui encontraras contenido pregrabado del podcas.</p>
             
            </div>
        </div>
    </section>

    <div class="album py-2 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="images/13.png" style="height:200px"></img>
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                </div>
                                <div class="col">
                                </div>
                                <a class="btn btn-primary" href="https://drive.google.com/file/d/1Q6ekDTj1FeysG5rnowzeD3S2GcrkVYWL/view?usp=drive_link"> ver video</a>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="images/12.png" style="height:200px"></img>
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                </div>
                                <div class="col">
                                </div>
                                <a class="btn btn-primary" href="https://drive.google.com/file/d/1pvYTjOZYzn6QqUCsFpuitGLtXw1qW9gf/view?usp=sharing"> ver video</a>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="col">
                    <div class="card shadow-sm">
                        <img src="images/11.png" style="height:200px"></img>
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">

                                </div>
                                <div class="col"> 

                                </div>
                                <a class="btn btn-primary" href="https://drive.google.com/file/d/1yYPph8AaJ9A5LeWG_upig2xi8G2kr4p6/view?usp=drive_link"> ver video</a>

                            </div>
                        </div>
                    </div>
                </div>

   

              
            </div>
        </div>
    </div>

</main>

PsicoApp/Views/Login/Index.cshtml
@{
    Layout=null;
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />

<section class="vh-100" style="background-color: #a0b9ff;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                           <img src="~/img/pisco.jpg" width="430" height="630" />
                                
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">

                                <form asp-controller="Login" asp-action="Index">

                                    <div class="d-flex align-items-center mb-3 pb-1">
                                        <i class="fas fa-cubes fa-2x me-3" style="color: #a0b9ff;"></i>
                                        <span class="h1 fw-bold mb-0">Podcast PsicoNutriologico</span>
                                    </div>

                                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Login</h5>

                                    <div class="form-outline mb-4">
                                        <input type="text" id="form2Example17" required  name="dni"class="form-control form-control-lg" />
                                        <label class="form-label"  for="form2Example17">DNI</label>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <input type="password" required id="form2Example27" name="password" class="form-control form-control-lg" />
                                        <label class="form-label" for="form2Example27">Contraseña</label>
                                    </div>

                                    <div class="pt-1 mb-4">
                                        <button class="btn btn-primary" type="submit" >Login</button>
                                    </div>

                                    <a class="small text-muted" href="#!">Olvido su contraseña?</a>
                                    <p class="mb-5 pb-lg-2" style="color: #a0b9ff;">
                                        No tienes cuenta? <a asp-action="Registro" asp-controller="Login" style="color: #a0b9ff;">Registrese aqui</a>
                                    </p>
                                    <div class="mb-4">
                                        <input type="checkbox" onclick="myFunction()"> Ver Contraseña
                                    </div>
                                 
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    function myFunction() {
        var x = document.getElementById("checkbox");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
</script>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

PsicoApp/Views/Login/Registro.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    Layout = null;
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />

<section class="vh-100" style="background-color: #a0b9ff;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img src="~/img/pisco.jpg" width="430" height="630" />

                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">

                                <form asp-controller="Login" asp-action="Registro">

                                    <div class="d-flex align-items-center mb-3 pb-1">
                                        <i class="fas fa-cubes fa-2x me-3" style="color: #a0b9ff;"></i>
                                        <span class="h3 fw-bold mb-0">Registro</span>
                                    </div>


                                    <div class="form-outline mb-2">
                                        <input type="text" id="form2Example17" required name="nombre" class="form-control form-control-lg" />
                                        <label class="form-label" for="form2Example17">Ingrese su Nombre</label>
                                    </div>
                                 
                                    <div class="form-outline mb-4">
                                        <input type="password" required id="form2Example27" name="password" class="form-control form-control-lg" />
                                        <label class="form-label" for="form2Example27">Ingrese una contraseña</label>
                                    </div>
                                    <div class="form-outline mb-1">
                                        <input type="password" required id="form2Example27" name="password" class="form-control form-control-lg" />
                                        <label class="form-label" for="form2Example27">Confirme la contraseña</label>
                                    </div>
                                    <div class="form-outline mb-1">
                                        <input type="number" id="form2Example17" required name="DNI" class="form-control form-control-lg" />
                                        <label class="form-label" for="form2Example17">Ingrese su DNI</label>
                                    </div>

                                    <div class="pt-1 mb-4">
                                        <button class="btn btn-primary" type="submit">Login</button>
                                    </div>
                                    <p class="mb-5 pb-lg-2" style="color: #4e7fea;">
                                        Tienes cuenta? <a asp-action="Index" asp-controller="Login" style="color: #4e7fea;">Logueate</a>
                                    </p>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    function myFunction() {
        var x = document.getElementById("checkbox");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

PsicoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PsicoApp</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PsicoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Podcast PsicoNutricional</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Consulta" asp-action="Index">Consultas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Galeria" asp-action="Index">Galeria de Contenido</a>
                        </li>
                        <div class="col">
                        </div>
                        <li class="nav-item">
                            <a class="btn btn-primary text-white"  asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        
                        <li class="nav-item">
                            <form class="d-flex" role="search">
                             
                                <button class="btn btn-danger" asp-controller="Home" asp-action="Index" type="submit">Salir</button>
                            </form>
                        </li>
                     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PsicoApp  <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>